CM/Controllers/ImportDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExcelDataReader;
using System.IO;
using CM.Models;
using System.Data;
using System.Data.Entity.Validation;
using Type = CM.Models.Type;
using Newtonsoft.Json;

namespace CM.Controllers
{
    public class ImportDataController : Controller
    {
        private ECMDBEntities db = new ECMDBEntities();
        // GET: ImportData
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
			System.Diagnostics.Debug.WriteLine("is upload");
			//System.Diagnostics.Debug.WriteLine(ModelState.IsValid.ToString() + upload.ToString());
			List<ImportCandidate> listEvent = new List<ImportCandidate>();
		List<ImportCandidate> listWarning = new List<ImportCandidate>();
		List<ImportCandidate> listError = new List<ImportCandidate>();
		List<ImportCandidate> ListAll = new List<ImportCandidate>();
			if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    Stream stream = upload.InputStream;
                    IExcelDataReader reader = null;
                    if (upload.FileName.EndsWith(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (upload.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    while (reader.NextResult())
                    {
                        if (reader.Name == "Sheet2")
                        {
                            reader.Read();
							int nline = 0;
							reader.Read();
							reader.Read();
							reader.Read();
							while (reader.Read())
                            {
								nline++;
								System.Diagnostics.Debug.WriteLine("is in Row" + nline.ToString());
								ImportCandidate curr = new ImportCandidate();
								//Candidate curr = new Candidate();
                             //   if (reader.GetString(3) == null) break;

			                   //  string str = string.Join(" ", reader.GetString(3).Split('(')[0].Split(' '));
								//	string	str = reader.GetString(3);
			     //                if (db.Universities.Where(o => o.UniversityName == str).Count() != 0)
			     //                {
								//	curr.Faculty_Of_University = str;
        ////                            University currU = new University();
        ////                            currU.Site = reader.GetString(1);
        ////                            currU.UniversityName = string.Join(" ", reader.GetString(3).Split('(')[0].Split(' '));
        ////                            currU.UniversityCode = reader.GetString(5);
        ////                            currU.HotKey = Convert.ToString(reader.GetValue(6));
        ////                            db.Universities.Add(currU);
        ////                            db.SaveChanges();
							 //    }
								//else
								//{
								//	System.Diagnostics.Debug.WriteLine("faculty is error" + nline.ToString());
								//	curr.Faculty_Of_University =null;
								//	curr.isErrorFaculty_of_University = true;
								//	curr.candidateType = Type.isError;
								//}
								curr.Account = reader.GetString(2);
								curr.National_id = Convert.ToInt32(reader.GetValue(0));
								curr.Gender = reader.GetString(6);
								curr.Email = reader.GetString(7);
								curr.Phone = Convert.ToString(reader.GetValue(8));
								curr.Facebook = reader.GetString(9);
								curr.CandidateName = reader.GetString(14);
								curr.DOB = Convert.ToDateTime(reader.GetValue(5));
								if (reader.GetValue(10).GetType()==typeof(DateTime))
								{
									curr.GraduationDate = Convert.ToDateTime(reader.GetValue(10));
								}
								else
								{
									System.Diagnostics.Debug.WriteLine("GraduationDate  error");
									curr.isErrorGraduationDate = true;
									curr.GraduationDate = null;
								}
								//if (reader.GetValue(11).GetType()==typeof(int))
								//{
									curr.WorkingTimeAvaiable = Convert.ToInt32(reader.GetValue(11));
								//}
								//else{
								//	System.Diagnostics.Debug.WriteLine("work fail");
								//	curr.isErrorWorkingTimeAvaiable = true;
								//	curr.candidateType = Type.isError;

								//}
								curr.Skill = reader.GetString(12);
								//if(reader.GetValue(38).GetType()==typeof(Double))
								//{
									curr.GPA = Convert.ToDouble(reader.GetValue(38));
								//}
								//else
								//{
								//	System.Diagnostics.Debug.WriteLine("gpa not null");
								//	curr.isErrorGPA = true;
								//	curr.GPA = null;

								//}
								//if(reader.GetValue(31).GetType()==typeof(int))
								//{
									curr.Faculty_of_University_id = Convert.ToInt32(reader.GetValue(32));
								//}
								//else
								//{
								//	System.Diagnostics.Debug.WriteLine("faculty of university fail");
								//	curr.isErrorFaculty_of_University_id = true;
									
								//}
								
								if (curr.candidateType == Type.isValid)
								{
									System.Diagnostics.Debug.WriteLine("add valid");
									listEvent.Add(curr);
								}
								else if (curr.candidateType == Type.isError)
								{
									System.Diagnostics.Debug.WriteLine("add error");
									listError.Add(curr);
								}
								else
								{
									System.Diagnostics.Debug.WriteLine("add warning");
									listWarning.Add(curr);
								}


								//                        str = reader.GetString(7).Split('-')[0];
								//                        if (db.Faculties.Where(o => o.FacultyCode == str).Count() == 0)
								//                        {
								//                            Faculty currF = new Faculty();
								//                            //System.Diagnostics.Debug.WriteLine(currF.id.GetType());
								//                            //System.Diagnostics.Debug.WriteLine(currF.FacultyCode.GetType());
								//                            //System.Diagnostics.Debug.WriteLine(currF.FacultyName.GetType());
								//                            currF.FacultyCode = reader.GetString(7).Split('-')[0];
								//                            currF.FacultyName = "khong biet";
								//                            db.Faculties.Add(currF);
								//                            db.SaveChanges();
								//                        }
								//                        Faculty_of_University currFU = new Faculty_of_University();
								//                        str = string.Join(" ", reader.GetString(3).Split('(')[0].Split(' '));
								//                        currFU.University_id = db.Universities.Where(o => o.UniversityName == str).First().id;
								//                        str = reader.GetString(7).Split('-')[0];
								//                        currFU.Faculty_id = db.Faculties.Where(o => o.FacultyCode == str).First().id;
								//                        currFU.Lv = Convert.ToInt32(reader.GetDouble(8));
								//                        if (db.Faculty_of_University.Where(o => o.University_id == currFU.University_id).Where(o => o.Faculty_id == currFU.Faculty_id).Count() == 0)
								//                        {
								//                            db.Faculty_of_University.Add(currFU);
								//                            db.SaveChanges();

								////str = reader.GetString(3);
								//if()

							}
							System.Diagnostics.Debug.WriteLine("list Valid Event:");
							foreach (ImportCandidate item in listEvent)
							{
								AddEventToDB(item);
								System.Diagnostics.Debug.WriteLine(
									
									item.CandidateName + " | " +
									item.Account + " | " +
									item.Email + " | " +
									item.Facebook + " | " +
									item.Phone + " | " +
									item.Gender + " | " +
									item.GraduationDate.ToString() + " | " +
									item.WorkingTimeAvaiable + " | " +
									item.Skill + " | " +
									item.GPA + " | " +
									item.Faculty_of_University_id + " | " +								
									item.National_id + " | " );
									//item.feedback + " | " +
									//item.feedbackContent + " | " +
									//item.feedbackTeacher + " | " +
									//item.feedbackOrganization + " | " +
									//item.note + " | " +
									//item.status + " | ");
							}
							System.Diagnostics.Debug.WriteLine("list Warning Event:");
							foreach (ImportCandidate item in listWarning)
							{

								System.Diagnostics.Debug.WriteLine(
									item.CandidateName + " | " +
									item.Account + " | " +
									item.Email + " | " +
									item.Facebook + " | " +
									item.Phone + " | " +
									item.Gender + " | " +
									item.GraduationDate.ToString() + " | " +
									item.WorkingTimeAvaiable + " | " +
									item.Skill + " | " +
									item.GPA + " | " +
									item.Faculty_of_University_id + " | " +
									item.National_id + " | ");
							}
							System.Diagnostics.Debug.WriteLine("list error Event:");
							foreach (ImportCandidate item in listError)
							{

								System.Diagnostics.Debug.WriteLine(
									item.CandidateName + " | " +
									item.Account + " | " +
									item.Email + " | " +
									item.Facebook + " | " +
									item.Phone + " | " +
									item.Gender + " | " +
									item.GraduationDate.ToString() + " | " +
									item.WorkingTimeAvaiable + " | " +
									item.Skill + " | " +
									item.GPA + " | " +
									item.Faculty_of_University_id + " | " +
									item.National_id + " | ");
							}
							ListAll.AddRange(listEvent);
							ListAll.AddRange(listWarning);
							ListAll.AddRange(listError);
							break;
						}

                        //tim sheet param
                        //if (reader.Name == "Param")
                        //{
                        //    //import campuslink

CM/Views/ImportData/Upload.cshtml
@{
	ViewBag.Title = "Upload";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
@using CM.Models


<h2>Import Data</h2>
@using (Html.BeginForm("Upload", "ImportData", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary()

	<div class="form-group">
		<input type="file" id="dataFile" name="upload" />
	</div>

	<div class="form-group">
		<input type="submit" value="Upload" class="btn btn-default" />
	</div>
}
<ul class="nav nav-tabs">
	<li class="active"><a data-toggle="tab" href="#success-tab"><span id="success-span" class="glyphicon glyphicon-ok text-green" style="width:150px;font-size: 18px;text-align:center"><b>Success(0)</b></span></a></li>
	<li><a data-toggle="tab" href="#warning-tab"><span id="warning-span" class="glyphicon glyphicon-alert text-yellow" style="width:150px;font-size: 18px;text-align:center"><b>Warning(0)</b></span></a></li>
	<li><a data-toggle="tab" href="#error-tab"><span id="error-span" class="glyphicon glyphicon-remove text-red" style="width:150px;font-size: 18px;text-align:center"><b>Error(0)</b></span></a></li>
</ul>

<div class="tab-content">
	<div id="success-tab" class="dataTables_wrapper form-inline dt-bootstrap tab-pane fade in active">
		<div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
		<div class="row">
			<div class="col-sm-12" style="overflow-x:scroll">
				<table id="success-data" class="table table-bordered table-hover dataTable" role="grid">
					<thead>
						<tr role="row">
							<th>name</th>
							<th>university</th>
							<th>faculty</th>
							<th>gender</th>
							<th>Email</th>
							<th>Phone</th>
							<th>Course_code</th>
							<th>Site</th>
							<th>Course_name</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
	<div id="warning-tab" class="dataTables_wrapper form-inline dt-bootstrap tab-pane fade">
		<div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row">
			<div class="col-sm-12" style="overflow-x:scroll">
				<table id="warning-data" class="table table-bordered table-hover dataTable" role="grid">
					<thead>
						<tr role="row">
							<th>name</th>
							<th>university</th>
							<th>faculty</th>
							<th>gender</th>
							<th>Email</th>
							<th>Phone</th>
							<th>Course_code</th>
							<th>Site</th>
							<th>Course_name</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
	<div id="error-tab" class="dataTables_wrapper form-inline dt-bootstrap tab-pane fade">
		<div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row">
			<div class="col-sm-12" style="overflow-x:scroll">
				<table id="error-data" class="table table-bordered table-hover dataTable" role="grid">
					<thead>
						<tr role="row">
							<th>name</th>
							<th>university</th>
							<th>faculty</th>
							<th>gender</th>
							<th>Email</th>
							<th>Phone</th>
							<th>Course_code</th>
							<th>Site</th>
							<th>Course_name</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@*<script type="text/javascript">
	function OnSuccess(response) {
		$('#success-data tbody').replaceWith(document.createElement('tbody'));
		$('#warning-data tbody').replaceWith(document.createElement('tbody'));
		$('#error-data tbody').replaceWith(document.createElement('tbody'));
		console.log('success upload');
		jsondata = $.parseJSON(response);
		var ns = 0;
		var nw = 0;
		var ne = 0;
		console.log(jsondata);
		for (var i in jsondata) {
			console.log(jsondata[i]);
			if (jsondata[i].eventType == 0) {
				ShowDataToTable(jsondata[i], '#success-data', i % 2);
				ns++;
			} else if (jsondata[i].eventType == 1) {
				ShowDataToTable(jsondata[i], '#warning-data', i % 2);
				nw++;
			} else {
				ShowDataToTable(jsondata[i], '#error-data', i % 2);
				ne++;
			}
		}
		$('#success-span b').text('Success(' + ns + ')');
		$('#warning-span b').text('Warning(' + nw + ')');
		$('#error-span b').text('Error(' + ne + ')');
	}
	function OnFailure(response) {
		alert("Error occured.");
	}
	function ShowDataToTable(data, tableId, i) {
		var row$ = $('<tr role="row"/>');
		if (i == 0) {
			row$.addClass("odd");
		} else {
			row$.addClass("even");
		}
		if (data.eventType == 2 && data.isErrorSite) {
			row$.append($('<td/>').html(data.site).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.site))
		}
		row$.append($('<td/>').html(data.courseCode));
		if (data.eventType == 1) {
			row$.append($('<td/>').html(data.changeCourseCode).addClass("bg-yellow"));
		}
		if (data.eventType == 2 && data.isErrorCourseName) {
			row$.append($('<td/>').html(data.courseName).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.courseName));
		}
		if (data.eventType == 2 && data.isErrorSubjectType) {
			row$.append($('<td/>').html(data.subjectType).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.subjectType));
		}
		if (data.eventType == 2 && data.isErrorSubSubjectType) {
			row$.append($('<td/>').html(data.subSubjectType).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.subSubjectType));
		}
		if (data.eventType == 2 && data.isErrorFormatType) {
			row$.append($('<td/>').html(data.formatType).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.formatType));
		}
		if (data.eventType == 2 && data.isErrorSupplierPartner) {
			row$.append($('<td/>').html(data.supplierPartner).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.supplierPartner));
		}
		if (data.eventType == 2 && data.isErrorPlannedStartDate) {
			row$.append($('<td/>').html(ConvertToDate(data.plannedStartDate)).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(ConvertToDate(data.plannedStartDate)));
		}
		if (data.eventType == 2 && data.isErrorPlannedEndDate) {
			row$.append($('<td/>').html(ConvertToDate(data.plannedEndDate)).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(ConvertToDate(data.plannedEndDate)));
		}
		row$.append($('<td/>').html(data.plannedExpense));
		if (data.eventType == 2 && data.isErrorActualStartDate) {
			row$.append($('<td/>').html(ConvertToDate(data.actualStartDate)).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(ConvertToDate(data.actualStartDate)));
		}
		if (data.eventType == 2 && data.isErrorActualEndDate) {
			row$.append($('<td/>').html(ConvertToDate(data.actualEndDate)).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(ConvertToDate(data.actualEndDate)));
		}
		row$.append($('<td/>').html(data.actualExpense));
		row$.append($('<td/>').html(data.budgetCode));
		if (data.eventType == 2 && data.isErrorStatus) {
			row$.append($('<td/>').html(data.status).addClass("bg-red text-light"));
		} else {
			row$.append($('<td/>').html(data.status));
		}
		//row$.append($('<td/>').html(data.feedback));
		//row$.append($('<td/>').html(data.feedbackContent));
		//row$.append($('<td/>').html(data.feedbackTeacher));
		//row$.append($('<td/>').html(data.feedbackOrganization));
		//row$.append($('<td/>').html(data.note));
		$(tableId).children('tbody').append(row$);
	}
	const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
	function ConvertToDate(datetime) {
		var day = new Date(datetime)
		if (day == null) {
			return "";
		}
		return monthNames[day.getMonth()] + '-' + day.getDay() + '-' + day.getFullYear();
	}
</script>*@